#cd ~/my_apps/vue3app

FROM node:22-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    libnspr4 libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 \
    libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 \
    libgbm1 libpango-1.0-0 libcairo2 libasound2 libatspi2.0-0 \
    libx11-6 libx11-xcb1 libxcb1 libxext6 libxi6 libxtst6 libgtk-3-0 \
    libgl1 libglx-mesa0 libglu1-mesa mesa-utils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
CMD ["npm", "run", "electron:dev"]
#DOCKER